-- Slice AI: lock atelier FX at quotation send; carry currency onto the commission.
ALTER TABLE "Quotation" ADD COLUMN IF NOT EXISTS "fxRateLocked" DOUBLE PRECISION;
ALTER TABLE "Quotation" ADD COLUMN IF NOT EXISTS "fxGbpRateLocked" DOUBLE PRECISION;
ALTER TABLE "Quotation" ADD COLUMN IF NOT EXISTS "fxRateSource" TEXT;
ALTER TABLE "Quotation" ADD COLUMN IF NOT EXISTS "fxRateFetchedAt" TIMESTAMP(3);
ALTER TABLE "Quotation" ADD COLUMN IF NOT EXISTS "fxRateStale" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Quotation" ADD COLUMN IF NOT EXISTS "fxUsdAmountLocked" DOUBLE PRECISION;
ALTER TABLE "Quotation" ADD COLUMN IF NOT EXISTS "fxGbpAmountLocked" DOUBLE PRECISION;

ALTER TABLE "BespokeOrder" ADD COLUMN IF NOT EXISTS "currency" TEXT NOT NULL DEFAULT 'NGN';
ALTER TABLE "BespokeOrder" ADD COLUMN IF NOT EXISTS "fxRateLocked" DOUBLE PRECISION;
ALTER TABLE "BespokeOrder" ADD COLUMN IF NOT EXISTS "fxGbpRateLocked" DOUBLE PRECISION;
ALTER TABLE "BespokeOrder" ADD COLUMN IF NOT EXISTS "fxRateSource" TEXT;
ALTER TABLE "BespokeOrder" ADD COLUMN IF NOT EXISTS "fxRateFetchedAt" TIMESTAMP(3);
ALTER TABLE "BespokeOrder" ADD COLUMN IF NOT EXISTS "fxRateStale" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "BespokeOrder" ADD COLUMN IF NOT EXISTS "fxUsdAmountLocked" DOUBLE PRECISION;
ALTER TABLE "BespokeOrder" ADD COLUMN IF NOT EXISTS "fxGbpAmountLocked" DOUBLE PRECISION;
